<?
/*
### 링크url ###
로그인						/member/login.php
로그아웃					/member/logout.php
회원가입					/member/join.php
마이페이지				/member/myinfo.php
장바구니					/shop/prd_basket.php
주문/배송조회			/shop/order_list.php
고객센터					/center/center.php
신상품						/shop/prd_list.php?grp=new
베스트상품				/shop/prd_list.php?grp=best
인기상품					/shop/prd_list.php?grp=popular
추천상품					/shop/prd_list.php?grp=recom
회사소개					/center/company.php
이용안내					/center/guide.php
개인정보취급방침	/center/privacy.php
사이트맵					/center/sitemap.php

상품목록					/shop/prd_list.php?catcode=000000

공지사항					/bbs/list.php?code=notice
고객문의					/bbs/list.php?code=qna
고객후기					/bbs/list.php?code=review
자주하는질문			/bbs/list.php?code=faq
*/
?>
	        </td>
	      </tr>
	    </table>
	    <!-- 가운데 영역 끝 -->

	    <!-- 퀵메뉴 -->
			<? include "$DOCUMENT_ROOT/inc/quick.inc"; ?>
			<!-- 퀵메뉴 끝 -->

		</td>
	</tr>
	<tr><td height="40"></td></tr>
  <tr>
    <td align="center" valign="top">

			<!-- 카피 부분 -->
			<table width="100%" height="28" cellpadding="0" cellspacing="0" border="0" background="/images/bottom_bg.gif">
				<tr>
					<td height="28" align="center">
						<table width="980" height="28" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td align="left" valign="middle">
									<table height="12" cellpadding="0" cellspacing="0" border="0">
										<tr>
											<td><a href="/center/company.php"><img src="/images/bottom_btn01.gif"></a></td>
											<td><a href="/center/guide.php"><img src="/images/bottom_btn02.gif"></a></td>
											<td><a href="/member/mall_info.php"><img src="/images/bottom_btn03.gif"></a></td>
											<td><a href="/member/join.php"><img src="/images/bottom_btn04.gif"></a></td>
											<td><a href="/center/privacy.php"><img src="/images/bottom_btn05.gif"></a></td>
											<!--td><a href="#"><img src="/images/bottom_btn06.gif"></a></td-->
										</tr>
									</table>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td align="center">
						<table width="980" height="80" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td align="left" valign="top"><img src="/images/bottom_logo.gif"></td>
								<td align="left" valign="top"><img src="/images/copy.gif"></td>
							</tr>
							<tr>
								<td colspan="2" align="right"><a href="/admin/" target="_blank"><img src="/admin/image/admin_login.gif" align="absmiddle" width="55" height="17" border="0"/></a></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
    	<!-- 카피 부분 끝 -->

    </td>
  </tr>
</table>
</body>
</html>